timezone: 'America/New_York'
languages: ['en', 'fr']
exclude_from_localizations: ['javascript', 'images', 'css']

baseurl: ""
permalink: /posts/:title/

sass:
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets
